### ISSUE TITLE
Rivet Basic Menu - Active menu option does not retain selected style (blue bottom border)

### ISSUE THREAD

**Issue by christiemh54** [indiana-university/rivet-source#142]
The new basic menu introduced into rivet does not maintain a selected state when a menu option is selected. 
https://rivet.iu.edu/components/navigation/menu/#

To reproduce: on the menu examples, simply select a different option than the default option shown. The new option does not show a selected state with a blue underline once selected:

![image](https://user-images.githubusercontent.com/47330881/62381298-2caf3300-b519-11e9-970a-9ee8a3ae5a38.png)

In the above screenshot, I just selected option4. My expectation is that option1 would become unselected and option4 would become selected with a blue bottom border.

This bug appears on every browser we tested (Firefox, Chrome, IE, Safari). In addition, on Safari, no focus border was displayed.

## Expected behavior
When a menu option is selected/clicked, the option should become in an active state and a blue bottom border should be shown under the option that is selected while other options should become unselected.

Also, we aren't sure if this is a bug or just the nature of the component demo, but when we click on an option, it takes us to the top of the page instead of changing the content below the menu and selecting that menu option.

**Comment by illusivesunrae** [comment]
@christiemh54 This component is intended to function as a menu. As a result, the underline will only appear under what is considered to be the "current page". Since this is a demo, the underline doesn't change when clicked because there is no navigation to a corresponding page. Thanks for reaching out. We appreciate you taking the time to discuss this with us.
