### ISSUE TITLE
Create Avatar Component

### ISSUE THREAD

**Issue by levimcg** [indiana-university/rivet-source#288]
Create a new stand-alone avatar component.

Rough specs:
- Should have a text-only/initials version similar to the existing Rivet header identity menu: https://rivet.iu.edu/components/navigation/header/#header-with-identity-menu
- Should have multiple size variants Eg. `-sm`, `-md-`, `-lg`, `-xl`
- Should be able to be nested inside quote and feed components Eg. Faculty profile pages, and feeds

## Updated February 12, 2020
Here's a quick codepen mockup I made while working on some layout experiments. 

https://codepen.io/levimcg/pen/ZEGbMgw

Some things to think about as we move this into the codebase:

1. How many size variants should we offer?
1. What kind of scale are the size variants based on? Eg. as they size up what is the multiplier? What is the default/base size ( `.rvt-avatar` ) with no modifier?
1. How do text-only variants work on dark backgrounds?
1. Should avatars have responsive variants? Eg. `rvt-avatar-lg-sm-up` (we might need to rethink our responsive class names 🙃 )

**Comment by levimcg** [comment]
Added a new prototype to the original issue posting ☝️

**Comment by zttodd** [comment]
@levimcg @illusivesunrae I'm working through this component now and have a few comments/questions for everyone. Check out the [feature/avatar](https://github.com/indiana-university/rivet-source/tree/feature/avatar) branch for the work so far.

> 1. How many size variants should we offer?

The sizes in the prototype appear to do a good job of covering most cases, but I'm not sure about the usefulness of the "small" variant of the image avatar, since the image will be so small that I don't think it's contributing anything meaningful to the surrounding messaging or content. Another use case that could come up is an XXL variant for profile listings. But that could be something that we address when we get to news/event/profile feeds?

> 2. What kind of scale are the size variants based on? Eg. as they size up what is the multiplier? What is the default/base size ( .rvt-avatar ) with no modifier?

In this branch, the component is outputting the variants in the order of "regular", "small", "medium", "large", and "extra large". I think it might be more consistent to have the "regular" option match another of the sizes, similar to how type-scale is sizing text.

> 3. How do text-only variants work on dark backgrounds?

There's an example layout for avatars on dark backgrounds.

> 4. Should avatars have responsive variants? Eg. rvt-avatar-lg-sm-up (we might need to rethink our responsive class names 🙃 )

Would this mostly apply to components that persist across breakpoints, like feeds, quotes, etc, rather than something like the identity module that disappears at a certain breakpoint?

Another way is to programmatically scale the avatar based on the viewport size, rather than breakpoints, so it will scale up and down to a min and max width based on the size of the browser window. But we wouldn't want these to resize if they're being used within a component that shouldn't resize the avatar, like the identity module.

**Comment by illusivesunrae** [comment]
Released with PR #355.
