### ISSUE TITLE
Duplicate Dialogs when performing a partial DOM, replacement/refresh. 

### ISSUE THREAD

**Issue by mtwagner** [indiana-university/rivet-source#681]
## Describe the bug
When performing a partial page refresh of the DOM, and the refreshed portion contains a Dialog, the dialog is move to be the first element of the body via method Dialog._makeDialogFirstElementInBody(). However, a subsequent refresh of that same section, will cause any newly contained dialogs to be also moved to be the first child of the body. There is no check to see if a dialog with that id has been moved to be the first child. This can result in non-unique id's in the DOM. This can occur when search results are updated, and contain a paired dialog (eg: Delete confirmation). Docs for Dialogs say "If for some reason the JavaScript that rearranges the dialog elements in the DOM causes issues with your application, you can render the dialog markup as the first child of body yourself using your templating engine of choice." But there seems to be no way of bypassing the move. 

## Expected behavior
Maintain unique id attributes by checking to see if dialogs with a given id have already been moved to be first child(ren) of body.

**Comment by levimcg** [comment]
@mtwagner thanks for reporting this. We'll take a lot and then track progress on it here in this issue.

**Comment by levimcg** [comment]
@mtwagner I think I understand part of the issue you're describing, but I'm not really sure I understand your specific situation well enough to be able to to test any solution we come up with to make sure that we're actually fixing your issue.

To be able to troubleshoot this we are going to need some sort of reduced test case at a URL we can access. Is there any way that you can put together a bare-bones demo that recreates the issue so that we can see it in a browser on our end?

**Comment by mtwagner** [comment]
Any movement on this one?

**Comment by levimcg** [comment]
@mtwagner I dropped the ball on this. I apologize.

I went back and looked at my notes and it could start to get problematic on our end to keep track of potentially duplicate dialogs and then try to clean up/remove the old existing dialogs before the new instance are re-rendered. It seems like it's better to leave that to your application logic.

Since you have control of the rendering/re-rending of the dialog each time you're refreshing a page, is there are reason you can clean up the existing dialog before you re-render the new one? The Rivet dialog will do all of it's own cleanup work of removing event listeners, etc. when you remove it from the DOM with your application logic.

I went back and found the the example code you sent me via DM, and in that case couldn't you grab a reference to the existing dialog and remove it from the DOM before re-rendering?

```js
function refreshContent() {
  const row = `
    <tbody id="results">
     ...rest of table markup...
  `
  // Grab a reference to the existing dialog and then removed from DOM
  const existingDialog = document.getElementById('dialog-confirmation')
  existingDialog.remove()

  // Replace with new markup
  $("#results").replaceWith(row)
}
```

Another option might be to keep the dialog in your example separate from the part of the DOM that you're re-rendering/refreshing and then "reuse" it each time. Especially if you're only using it to display a static warning message who's content isn't changing based on application logic. We do something similar to this in the docs for the [rivet icon library](https://rivet.iu.edu/icons/icon-library/).

We render a single dialog and then populate its contents based on which icon details button is clicked. The user can filter the list of icons which is similar to your "refresh" logic in the example you sent. But we only re-render the list, not the list and the dialog.

**Comment by mtwagner** [comment]
We ended up doing something like that. 
This issue re-arose for a different application, I ended up using the following work around locally.  

```
// Select the node that will be observed for mutations
var targetNode = document.getElementsByTagName('body')[0];

// Options for the observer (which mutations to observe)
var config = {childList: true };

// Callback function to execute when mutations are observed
var callback = function(mutationsList) {
    for(var mutation of mutationsList) {
        if (mutation.type == 'childList') {
			let existingDialogs = []
            let dialogs = document.querySelectorAll('[data-rvt-dialog]')
			dialogs.forEach(e => {
				if(existingDialogs.includes(e.id))
					e.remove()
				else
					existingDialogs.push(e.id)
			})
        }
    }
};

// Create an observer instance linked to the callback function
var observer = new MutationObserver(callback);

// Start observing the target node for configured mutations
observer.observe(targetNode, config);
```
