### ISSUE TITLE
Broken data-rvt-dialog-disable-page-interaction attribute

### ISSUE THREAD

**Issue by LittleWhiteLoti** [indiana-university/rivet-source#714]
## Describe the bug
The data-rvt-dialog-disable-page-interaction attribute doesn't appear to work.

## Expected behavior
I shouldn't be able to interact with the page when the modal is open as described in the documentation

## Relevant context (required)
HTML
![image](https://github.com/indiana-university/rivet-source/assets/61956115/15dfb3b3-3caf-4d78-b5ed-cacd92b35877)

Image
![image](https://github.com/indiana-university/rivet-source/assets/61956115/038495e2-dda7-453f-89df-a4b0aac611b3)

This happens in Firefox and Chrome so there is a good change is also happens in all other browser.

## Steps to reproduce
Add steps to reproduce the bug.
1. Create a modal dialog with the data-rvt-dialog-disable-page-interaction
2. Open the modal.
3. Click on the open modal again and it should close it.

**Comment by levimcg** [comment]
The disable page functionality is does not control the opening or closing of the dialog. It adds the `inert` and `aria-hidden` attributes to any siblings of the dialog element in the DOM. The `inert` attribute makes it so that the content underneath/behind the dialog is not reachable by keyboard navigation (using the Tab/Shift + Tab key), or assistive technology like screen readers. We also add the aria-hidden attribute as a fallback for browsers/screen reader combos that might not yet support the `inert` attribute.

In the steps you describe to reproduce the bug:

> 3. Click on the open modal again and it should close it.

Clicking on the dialog to close it is not related to the `data-rvt-dialog-disable-page-interaction`. As described in the documentation this attribute only disables interaction while the dialog is open (highlighted in screenshot)

<img width="848" alt="dialog javascript attribute documentation described previously" src="https://github.com/indiana-university/rivet-source/assets/5590034/e0fc7c03-6404-4a11-bf9e-2ff9ca55fba9">

If you have an actual use case or implementation that you could **provide a link for and describe what you are trying to accomplish**, that would be helpful. We can take a look at it and confirm whether the `data-rvt-dialog-disable-page-interaction` functionality is working as designed in your implementation. We have confirmed that the examples on the documentation site are working as expected.

**Comment by LittleWhiteLoti** [comment]
I think I misunderstood the documentation than. I thought it disabled all page interaction including the dialog  open button. Your first sentence explains what is actually going on.

**Comment by LittleWhiteLoti** [comment]
Thanks for the clarification.
