### ISSUE TITLE
Drop down navigation persistent highlight

### ISSUE THREAD

**Issue by geoffcashman** [indiana-university/rivet-source#749]
## Describe the bug
Using mouse-based interface, when the drop-down menu is activated, a highlight border appears around the first menu item. When hovering any menu item, the background changes to the same color as the border. Regardless of which menu item is hovered, the border highlight persists on the first menu item. This creates a confusing experience. Using keyboard interface, the border highlight moves with the item being focused. 

## Expected behavior
No border highlight border should appear until focus/hover moves to the first item, and the border should move with the item focused/hovered. 

I recognize that the focus element for keyboard interface is important for ADA concerns, but this creates a confusing experience for mouse-based interface. 

## Relevant context (required)
- https://rivet.iu.edu/layouts/preview/landing-page/landing-page/

![persistentborderissue](https://github.com/indiana-university/rivet-source/assets/169918603/3bbb05f4-f79c-49fc-932a-9b0327fa6a45)

**Comment by scottanthonymurray** [comment]
@mmeller75 To address this problem described in this issue, we're considering updating the Rivet dropdown component to focus on the first link in the dropdown *only if* the dropdown was opened via keyboard. Do you foresee any issues with this?

**Comment by mmeller75** [comment]
Thinking through audiences that may be impacted:

- Keyboard-only
- Mouse-only
- Touch: This is another pointer, but different from mouse in that there is no hover effect.
- Screen reader: This should mirror keyboard-only.
- Speech recognition: No hover effect.
- Switch control: I haven't personally used a switch control, but I think there wouldn't be a hover effect.
- Eye tracking: I don't have experience with this, so can't say for sure.

From the list above, there are other access methods than keyboard vs mouse that might benefit from having that focus outline to show where focus is but that don't have the hover effect. Although, it may not actually matter. 

Since I don't regularly use some of these input devices, I don't know for sure if people who do feel strongly one way or the other. 

The issue seems to be that the keyboard focus outline stays on the first item despite hover being over a different item. The main group this impacts is someone using a mouse or mouse-like control that has a hover effect.

Is it possible to instead move that focus on hover to follow hover? If that's possible, I wonder if that would be the best solution. 

The keyboard focus does help with identifying the dropdown that has opened. Because the outline around it is subtle, sometimes it's hard to see, so the focus helps me, at least, identify the thing that just opened.
