### ISSUE TITLE
Naming of the navigation toggle buttons could be improved

### ISSUE THREAD

**Issue by mmeller75** [indiana-university/rivet-source#757]
## Describe the bug
Currently, the toggle buttons used in navigation ([Header](https://rivet.iu.edu/components/header/?example=header-with-primary-navigation-secondary-navigation-and-search), [Sidenav](https://rivet.iu.edu/components/sidenav/?example=sidenav-with-dropdown-one-level-deep)) have verbose (and perhaps too technical) accessible names.

On the Header, the buttons are named "Toggle Sub-navigation". On the Rivet site, this button is named "Toggle "Documentation" Sub-navigation". 

On the Sidenav, the button has an even longer name: "Expand or hide links nested under the third section".

These are very verbose for screen reader and braille device users to read and for speech recognition users to speak. Shorter, more intuitive names would be more useful, especially since the buttons already use `aria-haspopup` to indicate that they have additional content and `aria-expanded` to indicate the expanded or collapsed state.

## Expected behavior
The accessible names should be concise, meaningful, and hopefully intuitive. Consider using:

- Something like "More [name of related link]"
- Using `aria-labelledby` to reference the id of the related link, as demonstrated on [Adrian Roselli's blog](https://adrianroselli.com/).

## Relevant context (required)
An example from [Adrian Roselli's blog](https://adrianroselli.com/) can be viewed in the navigation, on the disclosure button for navigation item "Blog".  A snippet of the relevant code:
`<li>
<a href="/posts" id="mnu2095">Blog</a>
<button type="button" id="btnSubblog" aria-controls="Subblog" aria-expanded="false" aria-labelledby="mnu2095">
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80" focusable="false" width="1em" height="1em" aria-hidden="true"><path d="M70.3 13.8L40 66.3 9.7 13.8z"></path></svg>
</button>
...
</li>`

Adrian also has a blog post describing the pattern he used along with his reasoning: [Link + Disclosure Widget Navigation](https://adrianroselli.com/2019/06/link-disclosure-widget-navigation.html).

## Steps to reproduce
Add steps to reproduce the bug.

1. Turn on a screen reader.
2. Listen to how the disclosure buttons are announced in the various navigation areas on [Rivet](https://rivet.iu.edu/components/).
3. Turn off the screen reader and turn on speech recognition software (Voice Control is available on both macOS and iOS; Voice Access is available on Android devices).
4. Try to activate one of the disclosure buttons with the accessible name. 
5. "Show names" on a mobile device (macOS does not support this functionality) and view the very long accessible names for the buttons.

**Comment by jameswilson** [comment]
@scottanthonymurray @levimcg This one got closed, but I was expecting to see some kind of a code change here, to know whether we need to update HTML for navigation toggles as an accessibility improvement.

Was there anything done here (maybe in another repository for the docs site)? If so, could someone link to an example showing the required fix?  

Thanks

**Comment by levimcg** [comment]
@jameswilson This was mostly a documentation/HTML example only update to the visually hidden button toggle labels in the Header and Subnav components. Based on the guidance from Meagan above, we've udated the HTML examples where nested navigation is used in these two components to use more succinct visually-hidden labels (for assistive technology) inside of the toggle buttons.

For example on the header example in the Rivet docs we've updated the label to this format `Show more {{ nav item text here }}` instead of the more verbose `Expand or hide links nested under the {{ nav item text here }} section` that we were using before (see original post above).

```html
<span class="rvt-sr-only">Show more section nav three links</span>
```

Here's a [link to the updated header](https://rivet.iu.edu/components/sidenav/?example=sidenav-with-dropdown-two-levels-deep) HTML example.

@scottanthonymurray and I talked and we'll also add a new bullet point to the "Accessibility" section of the the docs for the Sidenav and Header that gives more guidance on labelling and links back to this issue.
