### ISSUE TITLE
Radio and checkboxes inputs disappear when Rivet CSS is added

### ISSUE THREAD

**Issue by kennethj** [indiana-university/rivet-source#92]
## Describe the bug
If the label of a radio button is not the immediate next sibling, the radio button is hidden and no indicator of the status (selected/unselected) is displayed.

## Expected behavior
1. There would be affordances for other common radio button uses. Such as nesting the input in the label or putting the radio after the label.
2. The rivet css style would hide an input only if the rivet class is used on the input or label element, or the section is scoped
3. The radio input would failover to the default visible, instead of being hidden by default

## Relevant context (required)
https://github.com/indiana-university/rivet-source/blob/develop/src/sass/components/_radios.scss#L4-L8

### Examples
```html
<!-- nested input in label (implicitly associated)-->
<label><input type="radio" name="xyz" /> Option #1</label> 
<br />

<!-- label not immediate sibling -->
<span><input type="radio" id="foo" name="xyz" /></span>
<label for="foo"> Option #2</label> 
<br />

<!-- label before input -->
<label for="bar"> Option #3</label> <input type="radio" id="bar"  name="xyz" />
```
#### Result
<img width="165" alt="Screen Shot 2019-03-18 at 1 30 33 PM" src="https://user-images.githubusercontent.com/862054/54554256-0d58a480-4982-11e9-8a44-065f3880feb8.png">

#### Demo
![clicking-radio-buttons](https://user-images.githubusercontent.com/862054/54555723-421a2b00-4985-11e9-9b93-5651d74c2865.gif)

Note: This behavior also applies to checkbox inputs.

**Comment by levimcg** [comment]
Hey, @kennethj 

This is something that we intentionally design in the early days. Since we are creating customized checkboxes and radios, we decided to mostly standardize the way they should be marked up when using Rivet.

We decided agains implicit labeling (wrapping inputs with labels) because to the best of our knowledge and research programmatically labelling (`for`/`id` attribute combo) worked in the most reliable way across various browser/assistive technology combinations.

We did build in some styling flexibility for hidden inputs due to the way some popular framework template languages (ASP.NET Razor, I think???, Blade in Laravel, etc.) generate hidden inputs with some built-in template tags, but for the most part it seems like you should generally have control over your markup, excluding vendor products.

Is there a specific use case where you aren't able to mark up your forms the way we recommend in the docs?

**Comment by kennethj** [comment]
Use case: adding rivet to an existing application that already has many forms (some which are user generated) of which most do not have follow the rivet syntax.

I was assuming that the CSS could be updated to fail back to default styles if the Rivet syntax is not used. 

Something like:
```css
input[type='radio']:has(+ label){
 /* ... */
}
```

After trying to write some CSS overrides, I found the `:has()` pseudo-class is not yet supported by any browser yet, which makes the problem more difficult than I first expected.

Anyway, I can figure out other workarounds and overrides specific to the project I am working on. Any suggestions would be welcome.

**Comment by levimcg** [comment]
Aaaah, I see. Hmmm? I guess generally speaking, that would be more of the exception than the rule, so I'm hesitant to add more CSS to address those cases. 

I'd be happy to help out in whatever way I can though as you work through it. I'd also be interested to see what you come up with in terms of a workaround. 👍

**Comment by basham** [comment]
@kennethj If you could isolate the styling effects of Rivet to only parts of the DOM, would that make it easier for you? I feel like your issue would be much easier to work around if Rivet CSS was scoped (see #48).

**Comment by kennethj** [comment]
@basham Yeah. I saw that discussion. That feature would be useful in this instance.

**Comment by kennethj** [comment]
@levimcg  Right now I am just overriding the rivet CSS as I find other uses:
```css
label input[type=radio],
label input[type=checkbox],
label + input[type=radio],
label + input[type=checkbox] {
    position: inherit;
    left: auto;
    opacity: inherit;
}
```

Not pretty, or fancy.
